### ISSUE TITLE
[snapshot] Can't change to customer function: binary report

### ISSUE THREAD

**Issue by thopiekar** [openhab/org.openhab.binding.zwave#17]
When trying to change my DCH-Z510's operation mode to "binary report", I get a "HTTP Error -1" popping up and nothing changes. It doesn't matter which UI (Paper UI and HABmin2) I use. I readded (excluded, resetted the DCH-Z510 and included it again), without any changes.

```
2016-08-08 09:48:52.402 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 1 attempts left!
2016-08-08 09:48:52.403 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-08 09:48:52.414 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_ack changed from 167 to 168
2016-08-08 09:48:52.424 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_sof changed from 333 to 334
2016-08-08 09:48:52.439 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_sof changed from 334 to 335
2016-08-08 09:48:54.648 [INFO ] [marthome.event.ItemStateChangedEvent] - ipp_printer_Drucker_Airprint__waitingJobs changed from NULL to 0
2016-08-08 09:48:57.406 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 0 attempts left!
2016-08-08 09:48:57.407 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-08 09:48:57.418 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_ack changed from 168 to 169
2016-08-08 09:48:57.438 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_sof changed from 335 to 336
2016-08-08 09:48:57.449 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_8d1481bf_serial_sof changed from 336 to 337
2016-08-08 09:49:02.411 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=17, callback=122, payload=11 02 25 02
```

**Comment by cdjackson** [comment]
I don't know what the http error is or what the relevance is to the log? I would suggest to upgrade the a more recent runtime than beta 3 and if the problem still exists then provide a debug log.

**Comment by thopiekar** [comment]
Sorry, but https://github.com/openhab/openhab-distro/issues/264 is blocking here.

**Comment by thopiekar** [comment]
I updated to the recent snapshot, updated the binding and readded the controller and the siren. This is what I get here:

```
2016-08-20 16:52:54.399 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Connecting to serial port '/dev/ttyACM0'
2016-08-20 16:52:54.594 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Serial port is initialized
2016-08-20 16:52:54.595 [INFO ] [mmandclass.ZWaveSecurityCommandClass] - Update networkKey
2016-08-20 16:52:54.607 [INFO ] [ve.internal.protocol.ZWaveController] - Starting ZWave controller
2016-08-20 16:52:54.608 [INFO ] [ve.internal.protocol.ZWaveController] - ZWave timeout is set to 5000ms. Soft reset is false.
2016-08-20 16:52:57.998 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
2016-08-20 16:52:58.015 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 4: Node found
2016-08-20 16:52:58.018 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 6: Node found
2016-08-20 16:52:58.026 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 7: Node found
2016-08-20 16:52:58.036 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 9: Node found
2016-08-20 16:52:58.039 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 10: Node found
2016-08-20 16:52:58.044 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 11: Node found
2016-08-20 16:52:58.048 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 12: Node found
2016-08-20 16:52:58.056 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 13: Node found
2016-08-20 16:52:58.057 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 15: Node found
2016-08-20 16:52:58.061 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 17: Node found
2016-08-20 16:52:58.070 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 18: Node found
2016-08-20 16:52:58.072 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 19: Node found
2016-08-20 16:52:58.074 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
2016-08-20 16:52:58.075 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
2016-08-20 16:52:58.076 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
2016-08-20 16:52:58.078 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 13
2016-08-20 16:52:58.079 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
2016-08-20 16:53:00.682 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node17' to inbox.
2016-08-20 16:53:01.073 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node11' to inbox.
2016-08-20 16:53:02.040 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node9' to inbox.
2016-08-20 16:53:02.553 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node7' to inbox.
2016-08-20 16:53:03.087 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
2016-08-20 16:53:03.622 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node13' to inbox.
2016-08-20 16:53:04.363 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node19' to inbox.
2016-08-20 16:53:04.886 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node18' to inbox.
2016-08-20 16:53:05.603 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node10' to inbox.
2016-08-20 16:53:06.073 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node12' to inbox.
2016-08-20 16:53:06.735 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'zwave:device:f9088262:node4' to inbox.
2016-08-20 16:53:08.214 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 1 attempts left!
2016-08-20 16:53:13.216 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
2016-08-20 16:53:18.219 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Too many retries. Discarding message: Message: class=EnableSuc[0x52], type=Request[0x00], priority=High, dest=255, callback=0, payload=00 00 
2016-08-20 16:53:23.222 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
2016-08-20 16:53:28.225 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 1 attempts left!
2016-08-20 16:53:33.228 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
2016-08-20 16:53:38.231 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Too many retries. Discarding message: Message: class=SetSucNodeID[0x54], type=Request[0x00], priority=High, dest=255, callback=0, payload=01 00 00 00 01 
2016-08-20 16:53:45.388 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 4: Timeout while sending message. Requeueing - 0 attempts left!
2016-08-20 16:53:45.392 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 4: Got an error while sending data. Resending message.
2016-08-20 16:53:46.609 [ERROR] [alization.ZWaveNodeInitStageAdvancer] - NODE 4: Node advancer: Retries exceeded at DYNAMIC_VALUES
2016-08-20 16:53:52.117 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Initialising Thing Node...
2016-08-20 16:53:53.260 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Initialising Thing Node...
2016-08-20 16:53:53.338 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 2 attempts left!
2016-08-20 16:53:53.338 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-20 16:53:58.340 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 1 attempts left!
2016-08-20 16:53:58.342 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-20 16:54:03.347 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 0 attempts left!
2016-08-20 16:54:03.348 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-20 16:54:08.351 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Too many retries. Discarding message: Message: class=SendData[0x13], type=Request[0x00], priority=Get, dest=17, callback=32, payload=11 02 25 02 
2016-08-20 16:54:10.680 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Error getting configurationCommandClass
2016-08-20 16:54:10.687 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Error getting configurationCommandClass
2016-08-20 16:54:10.700 [ERROR] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Error getting configurationCommandClass
2016-08-20 16:54:11.009 [WARN ] [ding.zwave.handler.ZWaveThingHandler] - NODE 17: Initialising Thing Node...
2016-08-20 16:54:13.354 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 2 attempts left!
2016-08-20 16:54:13.355 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
2016-08-20 16:54:18.362 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 17: Timeout while sending message. Requeueing - 1 attempts left!
2016-08-20 16:54:18.364 [ERROR] [l.serialmessage.SendDataMessageClass] - NODE 17: Got an error while sending data. Resending message.
```

**Comment by thopiekar** [comment]
Also appended more messages I found in the logs.

**Comment by cdjackson** [comment]
Other than a few timeouts (which are quite common) I don’t see much of a problem. The configCommandClass message might be an issue, but without a debug log it’s impossible to say (and even with the debug log, it might not be obvious).

How does this relate to your reported problem of not changing the binary report?

Regarding the exception, I had hoped that this had been fixed in recent ESH versions, but if not I’m not sure how to resolve it. I don’t think it’s an issue with the binding, but again, without a log I’m afraid it’s hard to say.

**Comment by thopiekar** [comment]
Followed your instructions at http://www.cd-jackson.com/index.php/openhab/5-zwave-debugging-openhab and ran `log:set debug org.openhab.binding.zwave` .
After that it got a bit more verbose. Did I miss a command? Would be great if you could add it to the instructions on your website, so we (at least I) don't need to ask again.

**Comment by cdjackson** [comment]
That should be all that's required to get debug level messages from the zwave binding.

**Comment by thopiekar** [comment]
There are DEBUG messages on other nodes, but not on the relevant one. However, I give you now full access to my openhab.log* files. (openHAB2 is running on my NAS if it matters.)

https://www.myqnapcloud.com/smartshare/69237gkn4l6p7008uv2z1x3c_65YSKfC

**Comment by cdjackson** [comment]
Ah - I didn't realise you'd filtered the logs. This is always a bad idea as it filters information that is needed. If you only show lines that start with NODE x:, then it will filter out all received data and this is mandatory for debugging.

I'll have a look at the log...

**Comment by thopiekar** [comment]
Ok, sorry about this.

Thanks!

Mit freundlichen Grüßen/With kind regards
- Thomas Karl Pietrowski

Am 20.08.2016 10:17 nachm. schrieb "Chris Jackson" <notifications@github.com

**Comment by cdjackson** [comment]
Im trying to work out what your problem actually is. The title of this is "can't change to customer function: binary report" which I assume means that you can't set parameter 7 to 16?

What I need to see is a log that shows what happens when you try and do this - I can't really search through 100MB of logs to find this ;)

**Comment by thopiekar** [comment]
No problem. Correct, otherwise it is not possible to make the "switch" of the siren work. It will wait for a notification per default (Got no idea how to implement this. But, I'm interested, as the siren can play sounds, eg. like a "door bell", too.).

The last time stamp was `2016-08-20 21:11:01.499` before I was on the page of my thing via paper ui ( Configuration > Things > {Thing_name} )and did the following 3 times:
1. Went to the parameter settings
2. Changed parameter 7 to "sensor binary report"
3. Applied the change and got back to the first page
4. Reloaded the page (as it seemed to hang)
5. Waited until all channels were listed

Reloaded the log and the last time stamp is: `2016-08-20 21:18:17.598`

**Comment by cdjackson** [comment]
The logs don't appear to be very useful as there's still no debug for some reason.  Can you post the node17.xml file please? I'm wondering if there was some sort of problem during the discovery that means it's not properly discovered the device and there's no config class...

**Comment by thopiekar** [comment]
`distribution/userdata/zwave/nide17.xml`:

https://www.myqnapcloud.com/smartshare/69237gkn4l6p7008uv2z1x3c_6o823Gs

**Comment by cdjackson** [comment]
Ok - so as I thought - there’s no config class showing. Try deleting the XML and restarting OH and see if it regenerates with configuration this time. If not, we’ll need to look at why not (which will require a full log file during startup, and DEBUG logging will definitely be needed).

**Comment by thopiekar** [comment]
Already removed the xml before resuming our conversation here today.

I saw messages in the log that said that the binding wasn't able to
deserialize the XML. So I thought mine has an old layout and I remembered
that the XMLs are only 'caches', so I deleted it.

But can give it another try if you want. On startup it will generate a new
openhab.log isn't it?

My link above should show the recent openhab.log* files of my
userdata/logs/ ( actually it is directly linked to these files ) or is it
needed to get the log from the OH2 console?

**Comment by thopiekar** [comment]
This is the XML I had since beta3 (backed it up):

https://www.myqnapcloud.com/smartshare/69237gkn4l6p7008uv2z1x3c_6E752nt

**Comment by cdjackson** [comment]
One other thing to try then is to make sure that the network secure inclusion setting in the controller is set to either door locks. Or none. You need to enable advanced settings if using Habmin to see this. 

The log will be appended to when you restart - it's fine I can process this out. You shouldn't in theory need to look at the console log - the files should be fine. 

And yes the xml files are just a coach so deleting them is fine - since you've already done this id definitely try the secure setting (I saw some strange secure messages in your log which is why I mention this).

**Comment by thopiekar** [comment]
It was set to: `Entry Control Devices`. Can see it here from Paper UI.
Additionally, I saw that my controller is not set as "SUC", but it was in the past. So I enabled it again and set `network secure inclusion setting` to None. Now, I get ```OFFLINE  Node not found in Z-Wave network``` on every thing. I guess it was a bad idea making it a SUC again :eyes:
Disabled the SUC setting after that.

Ok, I'll try go for it... 
1. Shutting down OH2
2. Removing the node17.xml
3. Restarted OH2. The now it is: 00:44 (+02:00 timezone, so 22:44 in the logs)

**Comment by thopiekar** [comment]
Retried to change to "sensor binary report" (parameter 7) at approx 0:59 after node17.xml was found again.
The old link also works again: https://www.myqnapcloud.com/smartshare/69237gkn4l6p7008uv2z1x3c_6o823Gs

(Going to bed now. Thank you Chris for taking time :+1: )

**Comment by cdjackson** [comment]
I don’t think enabling SUC should make any problem, so maybe something else caused the devices to go offline. Also, when you do this, the binding will effectively restart, so everything will go offline for a little while.

Anyway, looking at the XML, it still doesn’t show CONFIG class. As it’s not in the NIF either, I guess the device is not reporting it. I have added a setting in the database for force this so let’s see if that solves this - I’ll do an update tonight, so please take another look with tomorrows binding. You will need to delete the XML and restart after updating the binding.

**Comment by thopiekar** [comment]
Hmm, I've set it again to SUC more than 6 hours ago (approx) and all things are still OFFLINE?
Sounds like a bug?

As I had problems jumping to the beta3 from an old snapshot, I resetted my siren. Is it possible that I've done it wrong? Or is there any other reason which could case my problem here?

**Comment by cdjackson** [comment]
Ok - I’ll need to see a log. Probably best to get a debug log during startup period.

SUC shouldn’t make much/any difference to the network, so there’s probably a bug in the binding…

**Comment by thopiekar** [comment]
So shutdown openHAB, `rm userdata/logs/openhab.log` and restart?

**Comment by cdjackson** [comment]
Yep.

**Comment by thopiekar** [comment]
Ok, the new log should be accessible via old link.

**Comment by cdjackson** [comment]
The log has no debug so it’s not especially useful.

I did find one bug as there’s an exception in the log and I can track this down - not sure that it’s actually the problem or not though.  Any chance of getting debug logging turned on and redoing this?

**Comment by thopiekar** [comment]
That's strange..
I'm sure I've set the zwave binding to debug. Also other extras don't
appear just ROOT. Don't know what happened here:

openhab> log:get
log:get
Logger | Level
--------------
ROOT   | WARN
openhab> log:set DEBUG
log:set DEBUG
openhab> log:get
log:get
Logger | Level
--------------
ROOT   | DEBUG

Is DEBUG globally to noisy?

**Comment by cdjackson** [comment]
Global is ok for me - I’ll process this with the log viewer and it will tell me most of what I need to know. If I need to actually read the log, then I use the log viewer to tell me the exact time…

If that’s the only way to get debug, then go for it...

**Comment by thopiekar** [comment]
Done. Log with global debugging is on since 18:51. So 16:51 in the logs.
(Hopefully nothing got resetted again...)

**Comment by cdjackson** [comment]
Well, I’m confused… This log still doesn’t have any zwave debug messages. It has debug for other bindings/core bundles, just not ZWave. I don’t know why that is - you don’t have any other configuration files have you - e.g. you haven’t edited the logbook file. I guess not, but something is stopping this from logging correctly...

**Comment by thopiekar** [comment]
Noticed that my openHAB just stopped yesterday. I waited for a new build from today, but had to start openHAB so I made a update to a yesterdays build.

As you can see there are DEBUG messages from yesterday:
```
2016-08-21 16:51:07.602 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (188): Starting destruction process
2016-08-21 16:51:07.603 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (188): Not an extended bundle or destruction of extension already finished
2016-08-21 16:51:07.604 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (188): Starting destruction process
2016-08-21 16:51:07.604 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (188): Not an extended bundle or destruction of extension already finished
```

Now restarted into console and found that my kind of "updating" (https://github.com/openhab/openhab-qnap-qpkg/blob/master/shared/openHAB.sh#L111) removes these settings: 
```
openhab> log:get
log:get
Logger | Level
--------------
ROOT   | WARN
```
Made a `log:set DEBUG` and restarted it as a service, while writing this comment.

**Comment by cdjackson** [comment]
Good luck - but as said earlier, while there were debug messages in the log there are no debug message from the zwave binding.

**Comment by thopiekar** [comment]
Hmm, but it seems to work now...
```
2016-08-22 21:16:44.699 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Starting destruction process
2016-08-22 21:16:44.699 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Not an extended bundle or destruction of extension already finished
2016-08-22 21:16:44.700 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Starting destruction process
2016-08-22 21:16:44.701 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Not an extended bundle or destruction of extension already finished
2016-08-22 21:16:47.998 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Stopped ZWave serial handler
2016-08-22 21:16:48.127 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Starting destruction process
2016-08-22 21:16:48.128 [DEBUG] [ell.impl.action.osgi.CommandExtender] - org.openhab.binding.zwave (198): Not an extended bundle or destruction of extension already finished
```

**Comment by cdjackson** [comment]
> On 22 Aug 2016, at 22:21, Thomas Karl Pietrowski <notifications@github.com> wrote:
> 
> Hmm, but it seems to work now...

No - there’s only INFO logging showing.

**Comment by thopiekar** [comment]
Oops, yes, you are right.

**Comment by thopiekar** [comment]
I reran `log:set debug org.openhab.binding.zwave` and now I have:
```
2016-08-22 21:27:35.662 [WARN ] [ore.internal.events.OSGiEventManager] - Dispatching event to subscriber 'org.eclipse.smarthome.core.thing.link.ThingLinkManager@132b7ca' takes more than 5000ms.
2016-08-22 21:27:35.850 [DEBUG] [org.openhab.binding.zwave           ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandler}={thing.type=zwave:dlink_dchz110_00_000, thing.id=zwave:device:f9088262:node13, service.id=342, service.bundleid=198, service.scope=singleton} - org.openhab.binding.zwave
2016-08-22 21:27:35.867 [DEBUG] [org.openhab.binding.zwave           ] - ServiceEvent REGISTERED - {org.eclipse.smarthome.config.core.status.ConfigStatusProvider}={service.id=343, service.bundleid=198, service.scope=singleton} - org.openhab.binding.zwave
```

**Comment by thopiekar** [comment]
It was truly a bug. Looks like log:get returns something completely wrong..

I'm just restarting openHAB as an service now, so I can close the SSH session.

**Comment by thopiekar** [comment]
Hey @cdjackson, can we take another look on this?

Thanks!

**Comment by cdjackson** [comment]
Sure. Just let me know...

**Comment by thopiekar** [comment]
Hey @cdjackson made an update of my snapshot today, set the logger to debug again and restarted OH2.

I also created a new link, so you can access /zwave and /log* under userdata.
https://www.myqnapcloud.com/smartshare/69237gkn4l6p7008uv2z1x3c_6j9o21i

I retried to change the customer function 3 times around 11:38.

**Comment by thopiekar** [comment]
Any news? :confused:

**Comment by cdjackson** [comment]
Sorry - I could find the point in the log. I only looked just now though and the only log around this time is the openhab_zwave.log file, but it stops at 11:37.

**Comment by thopiekar** [comment]
Ok, that's strange :confused:

**Comment by cdjackson** [comment]
I probably left it too long to download - it looks like the logs are live, and they have overwritten everything from yesterday other than the one that was renamed...

**Comment by thopiekar** [comment]
No problem. OH2 is running all the time - that's why I made the copy. I just didn't noticed the delay in the copied file.

Would it help if I remove all logs, start OH2, try to set the correct mode and shut OH2 down again (eg. after 10minutes), so you can look for the error messages without any stress?

**Comment by cdjackson** [comment]
A clean log would be good - so starting OH2, setting the parameter that doesn’t work, then copying the log somewhere so we know exactly what we’re looking at...

**Comment by thopiekar** [comment]
Removed all logs, restarted OH2, retried (17:23), waited for 5 minutes and turned it off.

**Comment by thopiekar** [comment]
Was there anything useful for you?

**Comment by cdjackson** [comment]
Sorry - I’ve not had a chance to look yet. I’m also trying to do a number of other things at the same time… I’ll try and look later this evening.

**Comment by thopiekar** [comment]
Ok, no problem. Will move the logs into a separate directory in the /logs.
Have to turn on OH2 soon to turn down my roller shutter. Will call the
directory simply "zwave" I think.

In the mean time, good luck on your other tasks 😉

**Comment by cdjackson** [comment]
What devices are node 17 and 18. It looks like a database problem for them.

**Comment by thopiekar** [comment]
```Z-Wave Node 18: FGRM222 Roller Shutter``` and ```Z-Wave Node 17: DCH-Z510 Siren```

**Comment by thopiekar** [comment]
By the way, node 17 is the device, whose parameter 7 I want to change to: `sensor binary report`.

**Comment by cdjackson** [comment]
I can guess that the siren might not support GET requests on the switch class - that might be the problem there. However the FGRM looks like it should respond to the parameter request.

For the siren, can you open the XML file (node17.xml) and change the following -:

      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <versionSupported>1</versionSupported>
        <isGetSupported>false</isGetSupported>
      </binarySwitchCommandClass>
    </entry>

note that the <isGetSupported> needs to be changed to false.

The other interesting this, which might explain your initial problem of not being able to set the config is that the device apparently doesn’t report that it supports the configuration command class. Let’s look at that next!

For the FGRM, you have a newer version than is in the database, and it possibly has different parameters. Can you have a scout around the internet and see if you can find a manual for version 25.25.

Cheers
Chris

**Comment by thopiekar** [comment]
Couldn't find any manual for firmware 25.25. Only (updated?) manuals mentioning 25.25 for other devices by Fibaro, like RGBW controller.
* http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=FIB_FGRM-222
Looks like I have to mail Fibaro for this...

For the siren I changed the file, removed all logs and restarted OH2, retried, shut OH2 down after 5min and  moved the logs to `zwave_2`.

**Comment by cdjackson** [comment]
I think it might be this -:

http://manuals.fibaro.com/content/manuals/en/FGR-222/FGR-222-EN-A-v1.00.pdf <http://manuals.fibaro.com/content/manuals/en/FGR-222/FGR-222-EN-A-v1.00.pdf>

This is listed as version 2.5, but I’ve seen in another Fibaro device (I forget which - the flood sensor I think) that they had version 2.2, but the version returned from the device was version 22.22. I wonder if this is some new ploy by Fibaro (no idea why).

Anyway… This manual doesn’t have a parameter 1, so if this is the device you have (it’s the most recent on the Fibaro website) then that would explain your problem…

**Comment by cdjackson** [comment]
I’ve created a new device in the database and copied this from the old version.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/413#parameters <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/413#parameters>

Can you please take a look through this and compare it to the manual for this version to see what needs to be added and deleted. If it needs to add any parameters, then it would be great if you can add them (if you have an account - if not, please create one and I’ll give you edit access). Anything that needs to be deleted will need to be done by me, so just let me know what parameters, if any, need to be deleted.

**Comment by thopiekar** [comment]
No need to add/remove any parameter here, but I had to correct ranges. Not only for the bools (0...1), but for other parameters.
Reviewed all the parameters and compared with the manual. Hope everything is fine now :wink:

**Comment by thopiekar** [comment]
Hey Chris,

I excluded the siren, made a factory reset and reincluded it to my network. Still can't change any parameter, but I can turn on the siren, but not off.
So I tried to apply what you've mentioned at https://github.com/openhab/org.openhab.binding.zwave/issues/17#issuecomment-244811522
but there is no `SWITCH_BINARY` anymore.

**Comment by cdjackson** [comment]
You mean swithc_binary is not in the XML file?

Can you provide a log showing you changing a parameter then waking up the device so that the exchange happens.

**Comment by thopiekar** [comment]
Of course. The log only says:
```
17.09.16 12:41			2016-09-17 10:41:35.154 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'OFF' for item 'zwave_device_f9088262_node25_switch_binary' to handler for channel 'zwave:device:f9088262:node25:switch_binary', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
17.09.16 12:41			2016-09-17 10:41:37.180 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate command 'ON' for item 'zwave_device_f9088262_node25_switch_binary' to handler for channel 'zwave:device:f9088262:node25:switch_binary', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
17.09.16 12:41			2016-09-17 10:41:37.186 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'ON' for item 'zwave_device_f9088262_node25_switch_binary' to handler for channel 'zwave:device:f9088262:node25:switch_binary', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
17.09.16 12:41			2016-09-17 10:41:39.161 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate command 'OFF' for item 'zwave_device_f9088262_node25_switch_binary' to handler for channel 'zwave:device:f9088262:node25:switch_binary', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
17.09.16 12:41			2016-09-17 10:41:39.168 [WARN ] [ome.core.thing.internal.ThingManager] - Cannot delegate update 'OFF' for item 'zwave_device_f9088262_node25_switch_binary' to handler for channel 'zwave:device:f9088262:node25:switch_binary', because no handler is assigned. Maybe the binding is not installed or not propertly initialized.
```

but I'll make a update to my snapshot and reset DEBUG on the zwave binding.

**Comment by cdjackson** [comment]
Not sure why that is! Maybe there’s an exception during startup or something - or maybe there’s some old configuration and this channel is no longer correctly specified?

**Comment by thopiekar** [comment]
Do you think it is worth to begin a new setup from the latest beta? :confused:

**Comment by cdjackson** [comment]
It shouldn’t be needed, but on the other hand, it would ensure that we know exactly what condition everything is in so yes, maybe its a good idea.

**Comment by thopiekar** [comment]
Guess what.. It works.. Simply everything, but turning off the siren..
(changing the parameters works at least)

And the log also looks promising:
```
2016-09-17 13:06:04.393 [DEBUG] [class.ZWaveConfigurationCommandClass] - NODE 25: Node configuration report, parameter = 7, value = 0, size = 1
2016-09-17 13:06:04.408 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Got an event from Z-Wave network: ZWaveConfigurationParameterEvent
2016-09-17 13:06:04.410 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Got a value event from Z-Wave network, endpoint = 0, command class = CONFIGURATION, value = org.openhab.binding.zwave.internal.protocol.ZWaveConfigurationParameter@11014bc
2016-09-17 13:06:04.413 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Update CONFIGURATION 7/1 to 0
2016-09-17 13:06:04.421 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Config about to update 4 parameters...
2016-09-17 13:06:04.424 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_31_1
2016-09-17 13:06:04.426 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_31_1 len=3
2016-09-17 13:06:04.439 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_31_1 - id = '31'
2016-09-17 13:06:04.445 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_29_1
2016-09-17 13:06:04.453 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_29_1 len=3
2016-09-17 13:06:04.454 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_29_1 - id = '29'
2016-09-17 13:06:04.458 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010
2016-09-17 13:06:04.464 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010 len=4
2016-09-17 13:06:04.465 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010 - id = '7'
2016-09-17 13:06:04.467 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010 - size = '1'
2016-09-17 13:06:04.470 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010 - bitmask = '00000010'
2016-09-17 13:06:04.471 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing config_7_1_00000010 - dec = '16'
2016-09-17 13:06:04.474 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Sub-parameter config_7_1_00000010 is 00000000
2016-09-17 13:06:04.477 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Pre-processing  00000000>>00000010
2016-09-17 13:06:04.481 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Post-processing 00000000>>00000010
2016-09-17 13:06:04.486 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Sub-parameter setting config_7_1_00000010 is 00000000 [0]
2016-09-17 13:06:04.488 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Processing binding_pollperiod
2016-09-17 13:06:04.508 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - UPDATE_DATABASE: Transaction complete (SendData:Request) success(true)
2016-09-17 13:06:04.527 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - checking initialisation queue. Queue size 0.
2016-09-17 13:06:04.536 [DEBUG] [curityCommandClassWithInitialization] - NODE 25: updating lastSentMessageTimestamp
2016-09-17 13:06:04.540 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
2016-09-17 13:06:04.544 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 25: Response processed after 356ms/4716ms.
2016-09-17 13:06:18.489 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Configuration update received
2016-09-17 13:06:18.502 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Configuration update group_1 to [node_1_0]
2016-09-17 13:06:20.802 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 25: Transaction not completed: node address inconsistent.  lastSent=25, incoming=255
2016-09-17 13:06:51.132 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 25: Transaction not completed: node address inconsistent.  lastSent=25, incoming=255
2016-09-17 13:06:51.557 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 25: Transaction not completed: node address inconsistent.  lastSent=25, incoming=255
2016-09-17 13:08:39.087 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Command received zwave:device:a831d790:node25:switch_binary --> ON
2016-09-17 13:08:39.088 [DEBUG] [dclass.ZWaveBinarySwitchCommandClass] - NODE 25: Creating new message for application command SWITCH_BINARY_SET
2016-09-17 13:08:39.098 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 25: Sending REQUEST Message = 01 0A 00 13 19 03 25 01 FF 25 43 41 
2016-09-17 13:08:39.117 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 25: Sent Data successfully placed on stack.
2016-09-17 13:08:39.186 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 25: SendData Request. CallBack ID = 67, Status = Transmission complete and ACK received(0)
2016-09-17 13:08:39.190 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - UPDATE_DATABASE: Transaction complete (SendData:Request) success(true)
2016-09-17 13:08:39.209 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - checking initialisation queue. Queue size 0.
2016-09-17 13:08:39.220 [DEBUG] [curityCommandClassWithInitialization] - NODE 25: updating lastSentMessageTimestamp
2016-09-17 13:08:39.228 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
2016-09-17 13:08:39.231 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 25: Response processed after 127ms/4716ms.
2016-09-17 13:08:39.886 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Command received zwave:device:a831d790:node25:switch_binary --> OFF
2016-09-17 13:08:39.887 [DEBUG] [dclass.ZWaveBinarySwitchCommandClass] - NODE 25: Creating new message for application command SWITCH_BINARY_SET
2016-09-17 13:08:39.921 [DEBUG] [ing.zwave.handler.ZWaveSerialHandler] - NODE 25: Sending REQUEST Message = 01 0A 00 13 19 03 25 01 00 25 44 B9 
2016-09-17 13:08:39.941 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 25: Sent Data successfully placed on stack.
2016-09-17 13:08:39.998 [DEBUG] [l.serialmessage.SendDataMessageClass] - NODE 25: SendData Request. CallBack ID = 68, Status = Transmission complete and ACK received(0)
2016-09-17 13:08:40.020 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - UPDATE_DATABASE: Transaction complete (SendData:Request) success(true)
2016-09-17 13:08:40.021 [DEBUG] [alization.ZWaveNodeInitStageAdvancer] - NODE 25: Node advancer - checking initialisation queue. Queue size 0.
2016-09-17 13:08:40.022 [DEBUG] [curityCommandClassWithInitialization] - NODE 25: updating lastSentMessageTimestamp
2016-09-17 13:08:40.025 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 25: Got an event from Z-Wave network: ZWaveTransactionCompletedEvent
2016-09-17 13:08:40.030 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 25: Response processed after 105ms/4716ms.
2016-09-17 13:09:10.351 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 25: Transaction not completed: node address inconsistent.  lastSent=25, incoming=255
2016-09-17 13:09:10.813 [DEBUG] [ssage.ApplicationCommandMessageClass] - NODE 25: Transaction not completed: node address inconsistent.  lastSent=25, incoming=255
```

The only interesting thing is that node25.xml is missing.

**Comment by cdjackson** [comment]
I would guess that the siren might not allow the OFF command unless security is enabled - but that’s a guess.

If you can get a full log from startup I’ll take a look at why the XML isn’t being generated.

At least we’re getting somewhere ;)

**Comment by thopiekar** [comment]
Restarted OH2 and since a while it stays at: "Node initialising: UPDATE_DATABASE"

**Comment by thopiekar** [comment]
[no_zwave_node25_logs_1.zip](https://github.com/openhab/org.openhab.binding.zwave/files/478174/no_zwave_node25_logs_1.zip)

**Comment by cdjackson** [comment]
Yep - also see that in the log. Not sure why but I’ll take a look as this stage shouldn’t get stuck for any significant time.

**Comment by thopiekar** [comment]
Btw. the siren is still blinking.

**Comment by cdjackson** [comment]
I don’t know what it means if the siren blinks.

There’s an exception in the update_database stage, so I’ll try and fix that now.

**Comment by thopiekar** [comment]
Ok, thanks :+1: 

I'll need to update to the snapshot tomorrow, isn't it?

**Comment by cdjackson** [comment]
I’ll create the fix now (I’ve found the bug) and will regenerate the binding - probably ready to go in about an hour if you update then.

**Comment by thopiekar** [comment]
Ok, great! No need to update to a snapshot?

**Comment by cdjackson** [comment]
Ref PR #108

**Comment by cdjackson** [comment]
Yes - you’ll need the latest snapshot, but as the nightly builds don’t work I need to trigger them manually which I’ll do as soon as the tests have run and the PR is merged. Once it’s then built, you should be able to use the snapshot (I think!)

**Comment by thopiekar** [comment]
:ok_hand:

**Comment by cdjackson** [comment]
Ok - this has finally built (after a test failure in another binding!).

**Comment by thopiekar** [comment]
It works! :heart_eyes:

**Comment by cdjackson** [comment]
:)

Great stuff.
